Change project structure #17
s-samusik/BookSharing pull request #18
Opened 2020-10-12 21:23 UTC by s-samusik

2020-10-13 14:23 UTC, N0menIllisLegio commented on BookSharing.BLL/Class1.cs
> +﻿using System;
Do we need this?

2020-10-13 14:25 UTC, N0menIllisLegio requested changes
Do we need empty files?

2020-10-13 14:25 UTC, N0menIllisLegio commented on BookSharing.Tests/UnitTest1.cs
> +using System;
And this

2020-10-13 22:56 UTC, s-samusik commented
I created empty projects to show main structure of solution. These classes need to be implemented in tasks #19.

2020-10-14 11:47 UTC, N0menIllisLegio approved these changes

2020-10-14 11:47 UTC, merged